# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16fc4dad74d3a757c7dc53991f827f5eedc1c959540fa1f69fe3e6d5e1f2d8abef3b958bb240676dc3b500e631f29abae218b70f71086119c0921fdef4d7cd8b

test:
  secret_key_base: 66df219dca0d4c95085969c87c4ac4b38fb9105122ee6c491dbc6c9918b594411d299260bd886efbd4a82a8a04101cc493a09b4afee2fd48d1b011f5a607320d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
